app/models.py
from . import db
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import current_user,UserMixin
from . import login_manager


class User (UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),unique = True,nullable = False)
    email = db.Column(db.String(255), unique = True,nullable = False)
    bio = db.Column(db.String(255),default ='My default Bio')
    profile_pic_path = db.Column(db.String(150),default ='default.png')
    hashed_password = db.Column(db.String(255),nullable = False)
    blog = db.relationship('Blog', backref='user', lazy='dynamic')
    comment = db.relationship('Comment', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def save_u(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()
    
    def __repr__(self):
        return f'User {self.username}'

    
class Blog(UserMixin,db.Model):
    __tablename__ = 'blogs'
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(255),nullable=False)
    content = db.Column(db.Text(),nullable=False)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comment = db.relationship('Comment', backref='blog', lazy='dynamic')

    def save_b(self):
        db.session.add(self)
        db.session.commit()

class Comment(UserMixin,db.Model):
    __tablename__='comments'

    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    blog_id = db.Column(db.Integer,db.ForeignKey("blogs.id"))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_c(self):
        db.session.add(self)
        db.session.commit()


    def delete(self):
        db.session.remove(self)
        db.session.commit()

    def get_comment(id):
        comment = Comment.query.all(id=id)
        return comment
    
    @classmethod
    def get_comments(cls,pitch_id):
        comments = Comment.query.filter_by(blog_id=blog_id).all()

        return comments


    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

class Subscriber(db.Model):
    __tablename__='subscribers'

    id=db.Column(db.Integer,primary_key=True)
    email = db.Column(db.String(255),unique=True,index=True)

    def save_subscriber(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'Subscriber {self.email}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,BooleanField,TextAreaField,PasswordField,SubmitField
from wtforms.validators import Required,Email,EqualTo
from ..models import User,Blog,Comment
from wtforms import ValidationError


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')


class BlogForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    blog = TextAreaField('Your Blog', validators=[Required()])
    submit = SubmitField('post')

class CommentForm(FlaskForm):
    comment = TextAreaField('Leave a comment',validators=[Required()])
    submit = SubmitField('Comment')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from config import config_options
from flask_login import LoginManager
from flask_mail import Mail
from flask_simplemde import SimpleMDE
from flask_uploads import UploadSet,configure_uploads,IMAGES


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db =SQLAlchemy()
mail = Mail()
photos = UploadSet('photos',IMAGES)
simple = SimpleMDE()


def create_app(config_name):
    app = Flask(__name__)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint) 

# Creating the app configurations
    app.config.from_object(config_options[config_name])

# configure UploadSet
    configure_uploads(app,photos)


#initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)


    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from .views import *

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,flash
from flask_login import login_required,current_user
from ..models import Blog,Comment,User,Subscriber
from .forms import BlogForm,CommentForm,UpdateProfile
from .. import db,photos
from . import main
from ..email import mail_message
import markdown2

@main.route('/')
def index():
    """
    views root page function that returns the index page
    """
    return render_template('index.html')


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(author = uname).first()
    if user is None:
        abort(404)
    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(author = uname).first()
    if user is None:
        abort(404)
    form = UpdateProfile()
    if form.validate_on_submit():
        user.bio = form.bio.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.profile',uname=user.author))
    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(author = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/comment/<blog_id>', methods = ['Post','GET'])
@login_required
def comment(blog_id):
    blog = Blog.query.get(blog_id)
    comment =request.form.get('newcomment')
    new_comment = Comment(comment = comment, user_id = current_user._get_current_object().id, blog_id=blog_id)
    new_comment.save()
    return redirect(url_for('main.blog',id = blog.id))


@main.route('/subscribe',methods = ['POST','GET'])
@login_required
def subscribe():
    email = request.form.get('subscriber')
    new_subscriber = Subscriber(email = email)
    new_subscriber.save_subscriber()
    mail_message("Subscribed to Blog App","email/welcome_subscriber",new_subscriber.email,new_subscriber=new_subscriber)
    flash('Sucessfuly subscribed')
    return redirect(url_for('main.index'))


@main.route('/blog/<blog_id>/update', methods = ['GET','POST'])
@login_required
def update_blog(blog_id):
    blog = Blog.query.get(blog_id)
    if blog.user != current_user:
        abort(403)
    form = CreateBlog()
    if form.validate_on_submit():
        form.title= form.title.data
        form.content= form.content.data
        db.session.commit()
        flash("Your post has benn updated!")
        return redirect(url_for('blog', blog_id=blog_id)) 
    elif request.method == 'GET':
        form.title.data = blog.title
        form.content.data = blog.content
    return render_template('create_blog.html', form = form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/blog.html
{% extends 'base.html'%}

{% block content %}
<body>

    <a href="">
        <aside class="dates" style="color: black;">26/02/2003</aside>
    </a>

    Pitch fork
    <p class="card-text">Pitch fork is one of the most popular music resources on the web. This online music magazine, which has come to be known as the most trusted voice in music,
        covers a variety of genres from indie rock, metal, and experimental music to electronic, pop, and hip-hop. </p></br>
       
        <a href="">
            <aside class="dates" style="color: black;">08/12/2017</aside>
        </a>


    Hypebot  
    <p class="card-text">s a great source of information on music, music technology, and the music business. This blog provides a lot of interesting news and insight on new technologies that musicians can use to publish their music and improve their reach,
        so Hypebot is definitely for people a bit more interested in the industry, behind-the-scenes.</p></br>
        

  </div>
</div>


<div class="col-md-3 ">
    <h4>All Comments</h4>
    {% for comment in comments %}
        <p class="mt-10"><span style="font-weight: bold">{{comment.user.username}} : </span> {{comment.comment}}</p>
    {% endfor %}
</div>
</div>  
<hr>      
</div>
<div class="col-md-1"></div>
</div>
</div>

<div class="modal fade" id="modalConfirmDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
aria-hidden="true">
<div class="modal-dialog modal-sm modal-notify modal-danger" role="document">
<div class="modal-content text-center">
<div class="modal-header d-flex justify-content-center">
<p class="heading">Are you sure?</p>
</div>
<div class="modal-body">
<i class="fas fa-times fa-4x animated rotateIn"></i>
</div>
<div class="modal-footer flex-center">
<form action="{{url_for('main.delete_post',blog_id = blog.id)}}" method="POST">
<input  type="submit" class="btn  btn-outline-danger btn-sm" value="Yes">
</form>
<a type="button" class="btn btn-sm btn-danger waves-effect" data-dismiss="modal">No</a>
</div>
</div>
</div>
</div>

<div class="modal fade" id="modalComment" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
aria-hidden="true">
<div class="modal-dialog modal-notify modal-info" role="document">
<div class="modal-content text-center">
<div class="modal-header d-flex justify-content-center">
<p class="heading">Leave A comment Here</p>
</div>
<div class="modal-body">
<form class="form" action="{{url_for('main.comment',blog_id = blog.id)}}" method="POST">
<div class="form-group green-border-focus">
<label></label>
<textarea class="form-control" placeholder="Type your comment..." rows="2" name ="newcomment" required></textarea>
</div>
<div class="modal-footer flex-center">
<button class="btn btn-sm btn-outline-success">Comment</button>
<a type="button" class="btn btn-outline-danger btn-sm " data-dismiss="modal">Exit</a>
</div>
</form>
</div>


</div>
</div>
</div>

</body>

{% endblock %}

app/templates/comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<body>
<br><br> <br>
<h3 class="text-center" ><u>New Comments</u></h2>
  {% for comment in comment[::-1] %}
  <div class="container">
    <div class="row">
      <div class="col-md-4"></div>
        <div class="card-groups">
          <div class="card">

            <div class="card-body">
              <p class="card-text">{{comment.comment}}.</p>
            </div>

            <div class="card-footer bg-transparent border-success"><small>Published on:{{comment.date_posted.strftime('%Y-%m-%d %H:%m')}}</small></div>
          </div>
    
      <div class="col-md-4"></div>
    </div>  
  {% endfor %}
</body>
  {% endblock %}

app/templates/create_blog.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}


<div class="col-md-2"></div>
        </div>
    </div>{% block content %}

    <div  i="particles-js"  >  
        <div class=" row" >
                
            <div class="col-md-2"></div>
            <div class="col-md-8" id="postform">
                <h2 class="text-center">Create Your Blog Here!</h2>
                {% if post%}
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Email address</label>
                    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                  </div>
                  <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Example textarea</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                  </div>            
                </div>
   
{% endblock%}

app/templates/index.html
{% extends 'base.html'%}


{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}


{% block content %}


<div class="container-fluid">
    <div class="col-md-3"></div>
    {% for message in get_flashed_messages() %}
    <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
    </div>
    {% endfor %}
    <form class="form-inline ml-2" action="{{url_for('main.subscribe')}}" method="POST">
        <div class="md-form form-group">
            <label class="white-color" style="color: white;">Name</label>
            <input type="name" style="color: black;" class="form-control " name ="subscriber" required>
            <label class="white-color" style="color: white;">Email Address...</label>
            <input type="email" style="color: black;" class="form-control " name ="subscriber" required>
        </div>

        <div class="md-form form-group">
            <button class="btn btn-sm btn-outline-info" id="subs" style="color: black; margin: 10px;">Subscribe</button>
        </div>
    </form>
</div>
</div>
</div>

  <h2 class="text-center" style="color: blueviolet; font-size: xx-large;font-family: 'Yesteryear', cursive, serif;"><u>Blogs ,Quotes</u></h2>
  
    <body>
        
  <div class="container">  
    <div class="d-flex justify-content-center row">
      <div class="card-groups">
        <div class="card border-info mb-3 col-md-4" style="max-width: 35rem;">          
          <div class="card-body">
            <h5 class="card-title" style="color: #dda0dd;"><u>Blogs </u></h5>
            
            <a href="">
                <aside class="dates" style="color: white;">26/02/2003</aside>
            </a>

            <p style="color: white;">Pitch fork</p>
            <p class="card-text" style="color: white">Pitch fork is one of the most popular music resources on the web. This online music magazine, which has come to be known as the most trusted voice in music,
                covers a variety of genres from indie rock, metal, and experimental music to electronic, pop, and hip-hop. </p></br>
               
                

            <p style="color: white;">Hypebot </p> 
            <p class="card-text" style="color: white">s a great source of information on music, music technology, and the music business. This blog provides a lot of interesting news and insight on new technologies that musicians can use to publish their music and improve their reach,
                so Hypebot is definitely for people a bit more interested in the industry, behind-the-scenes.</p></br>
                <a href="">
                    <aside class="dates" style="color: white;">08/12/2017</aside>
                </a>
                    </div>
                    </div>
                </div>
            </div>
            </div>


            <div class="container">  
            <div class="d-flex justify-content-center row">
            <div class="card-groups">
            <div class="card border-info mb-3 col-md-4" style="max-width: 35rem;">         
                <div class="card-body">   
            <h5 class="card-title" style="color:plum;"><u>Quotes </u></h5>
            <a href="">
                <aside class="dates" style="color: white;">31/07/2005</aside>
            </a>
            <p class="card-text" style="color: white">“If Java had true garbage collection, most programs would delete themselves upon execution.”
               <p style="color: plum;  font-family: 'Architects Daughter', cursive;">— Robert Sewell</p> 
                </p></br>


                <a href="">
                    <aside class="dates" style="color: white;">21/01/2019</aside>
                </a>
            <p class="card-text" style="color: white;">“QA Engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.”
               <p style="color: plum;  font-family: 'Architects Daughter', cursive;"> — Bill Sempf</p>
                </p></br>

                <a href="">
                    <aside class="dates" style="color: white;">08/12/2017</aside>
                </a>

            <p class="card-text" style="color: white;">“XML is like violence – if it doesn’t solve your problems, you are not using enough of it.”

                <p style="color: plum;  font-family: 'Architects Daughter', cursive;"> — Bridgit Roberts</p>
                </p><b/r>

                <a href="">
                    <aside class="dates" style="color: white;">08/05/2017</aside>
                </a>

            <p class="card-text" style="color: white;">“Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.”
                <p style="color: plum;  font-family: 'Architects Daughter', cursive;"> — Rick Osborne</p>
                </p></b>
                <a href="">
                    <aside class="dates" style="color: white;">09/10/2001</aside>
                </a>

            <p class="card-text" style="color: white;">“There are only two kinds of programming languages: those people always bitch about and those nobody uses.”
                <p style="color: plum;  font-family: 'Architects Daughter', cursive;">— Bjarne Stroustrup</p>
            </p></br>

                <a href="">
                    <aside class="dates" style="color: white;">08/12/2014</aside>
                </a>    
            <p class="card-text" style="color: white;">“Some people, when confronted with a problem, think “I know, I’ll use regular expressions.” Now they have two problems.”

                <p style="color: plum;  font-family: 'Architects Daughter', cursive;"> — Jamie Zawinski</p>
            </p></br>
              
        </div>
        </div>
        </div>
        </div>
        </div>
    
    </body>
  {% endblock%}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation"  >
  <div class="container-fluid">
      <div class="navbar-header" style="width: 280px;">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"> Blogs App</a>
      </div>
      <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              <li><a href="/">Home</a></li>

              
      </div>

  </div>
</div>

<ul class="nav navbar-nav navbar-right">
  {% if current_user.is_authenticated %}
  <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
  {% else %}
  <li><a href="{{url_for('auth.login')}}">Sign in</a></li>


  {%endif%}
</ul>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>

<div class="col-md-4">
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}